### ISSUE TITLE
Testing Makefile -- unifdef breaks on OSX

### ISSUE THREAD

**Issue by krs-world** [krs-world/Bridges_Testing#17]
unifdef   doesnt have a -x option on OSX and breaks.  This is in teh 
c++/web_tutorial_mastercopy/Makefile

**Comment by esaule** [comment]
unifdef has supported -x for years. A blame against the source code https://github.com/fanf2/unifdef/blame/master/unifdef.c show that the -x option is at least 6 years old.

**Comment by esaule** [comment]
fixed.
