### ISSUE TITLE
Testing - Update..

### ISSUE THREAD

**Issue by krs-world** [krs-world/Bridges_Testing#21]
With the pushed version of the tests. I can run tests in all 3 languages with teh following caveats:

C++ - the unifdef issue on OSX  (see the issue related to that)
JSON error in the Lyrics test (but visualization seems fine)
Python - tests are fine, but need conversion to have a main function(see issue on that).

**Comment by esaule** [comment]
the C++ issue and the python issue should be both fixed.

The JSON was against the java client and is fixed against clone now.
Closing this issue.
