### ISSUE TITLE
Python tests updated with main()

### ISSUE THREAD

**Issue by krs-world** [krs-world/Bridges_Testing#22]
Matthew/Alex:

Could you all check these tests? We need the Makefile to work with teh ifdefs so only the master copy has been modified. Teh unifdef command popoulations the two target directories..I just edited the master copy of the tests to now call main().  Once Erik fixes Makefile, we might be able to test, though it should run on Linux (unifdef issue).

**Comment by krs-world** [comment]
Matthew, add tests only to the MasterCopy directory under python. Teh other two are automatically generated. If you added any you should copy that to the mastercopy directory and then add the TESTING directives that is needed by the Makefile

**Comment by esaule** [comment]
The makefile should work automatically for python now. If uses the existence of a "def main" to chose which files to run.
