### ISSUE TITLE
Update Python tests to use new module names

### ISSUE THREAD

**Issue by AlecGoncharow** [krs-world/Bridges_Testing#24]
The bridges-python modules have been renamed to match Python naming guidelines
https://github.com/krs-world/bridges-python/commit/11d68b0e44c602d0d8756cad6162cafabbc5fd3d
https://www.python.org/dev/peps/pep-0008/#package-and-module-names
All tests will need to take these new module names into account

**Comment by esaule** [comment]
Did you also change the name of all functions to snake case? Like setTitle to set_title?

**Comment by AlecGoncharow** [comment]
Thats a wip, new functions will be snake_case but there are a lot of function using camelCase, I will change them soon, I just wanted to rename modules to prevent as many merge conflicts as possible. I think it is safe to assume snake case and camelCase should be considered a bug/issue.

**Comment by AlecGoncharow** [comment]
I have gone through and replaced any camelCase functions with snake_case.
https://github.com/krs-world/bridges-python/pull/23

**Comment by esaule** [comment]
It wasn't really the time to make that kind of change. But now that we are at it. Let's make all necessary changes. I updated the module names in the tests but a lot of other things broke.

**Comment by AlecGoncharow** [comment]
Are the errors all related to the function name or are there other errors?
