### ISSUE TITLE
gitignore generated directories/files

### ISSUE THREAD

**Issue by squeetus** [krs-world/Bridges_Testing#28]
Which subdirectories can we add to the gitignore file? As per [this issue I posted](https://github.com/krs-world/Bridges_Testing/issues/23), I would find a brief description of each of the subdirectories' purposes very helpful, as the names are a bit confusing to me. A few tweaks to the gitignore file would keep my untracked files clean after running 'make' to run the tests and would make life a bit easier.

**Comment by krs-world** [comment]
The only directories that need to be pushed is the 
webtutorial_mastercopy and data_src_dependent. The 
website_tutorial_testing and website_tutorial_fortheweb are 
automatically generated.

     -- krs

**Comment by squeetus** [comment]
Updated in this commit: https://github.com/krs-world/Bridges_Testing/commit/d3be9d3859eadf4a4196abc68f680a553d88d64a
