### ISSUE TITLE
test updates..

### ISSUE THREAD

**Issue by krs-world** [krs-world/Bridges_Testing#5]
Added tests for symbol collection and kd tree (both C++ and Java should be synced now).

I think I have the Makefiles set up right. Good idea to pull and test. You should be able to ideally do 

make 
make run 

to run all the tests. It assumes an env_vars.mk file that contains the needed constants for paths/variables.

It uses:

BRIDGES_HOME = 
BRIDGES_INCL = $(BRIDGES_HOME)/cxx/src

CURL_HOME = 
CURL_INCL = $(CURL_HOME)/include
CURL_LIB_PATH = $(CURL_HOME)/lib
CURL_LIB = curl

RAPID_JSON_HOME = 
RAPID_JSON_INCL = $(RAPID_JSON_HOME)/include

BRIDGES_TESTING_USER_NAME = bridges_testing
BRIDGES_TESTING_API_KEY = 
BRIDGES_SERVER =   // use the clone server

BRIDGES_PUBLIC_USER_NAME = bridges_public
BRIDGES_PUBLIC_API_KEY =

**Comment by krs-world** [comment]
Good idea to give it a test. It will use  the following sequence

100+   C++ basic tests
300+  C++ data source relevant tests
200+ Java basic
400+  Java data source

Python (not done)
500+   Basic
600+   data source

**Comment by krs-world** [comment]
I meant assignment numbers.

Do not change the C++ basic tests code (it has a a TESTING ifdef) I mirror that wiht the website tutorials. To automate the process I just remove the ifdef parts (using the unifdef command -- who knew?!, but very convenient to automate!)

**Comment by esaule** [comment]
same as the recently posted issue. Closing this one.
